Repository clearlinux/mixer-tools, pull requests merged in 2018-05, with the labels that each got.

#277 Declare local error for fullfile creation
  swupd/fullfiles.go
Labels: bug

#286 Remove unused pack scripts
  Makefile
  mixer/cmd/build.go
  pack-maker.sh
  superpack-maker.sh
Labels: janitorial

#287 Add mixer manual pages
  Makefile
  docs/mixer.1
  docs/mixer.1.rst
  docs/mixer.add-rpms.1
  docs/mixer.add-rpms.1.rst
  docs/mixer.build.1
  docs/mixer.build.1.rst
  docs/mixer.bundle.1
  docs/mixer.bundle.1.rst
  docs/mixer.config.1
  docs/mixer.config.1.rst
  docs/mixer.init.1
  docs/mixer.init.1.rst
  docs/mixer.repo.1
  docs/mixer.repo.1.rst
  docs/mixer.versions.1
  docs/mixer.versions.1.rst
Labels: documentation

#295 Compress Manifest.full as well
  builder/builder.go
Labels: bug

#288 swupd: clean up manifest creation
  swupd/create_manifests.go
Labels: janitorial

#292 Add man page for mixin
  Makefile
  docs/mixin.1
  docs/mixin.1.rst
Labels: documentation

#296 Create man page directory if it doesn't exist
  Makefile
Labels: bug

#306 Add tutorial for adding custom content from build root
  docs/tutorials/custom-content-from-chroot.md
Labels: documentation
